version: '3.9'
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: gmtq-sqlserver
    ports:
      - 1433:1433
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=VeryStr0ng@Pass

  redis:
    image: redis:7.0-alpine
    container_name: gmtq-redis
    restart: unless-stopped
    command: redis-server --requirepass admin
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: gmtq-redis-gui
    restart: unless-stopped
    ports:
      - 16379:8001
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis


volumes:
  redis-data:
    driver: local
  redisinsight-data:
    driver: local
  redis:
    driver: local
  mssqlsystem:
    driver: local
  mssqluser:
    driver: local
